# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 75c7783a68bbb2973fcb29cde570930d42b247f8d08bb6d08b7e7650b7ea04a395cc04b69b8a2ecf2db0e8b7fb823de2079fa9b0d8e7ff75b1f93952846d016a

test:
  secret_key_base: 3a51b5860585a72e2cfcb3856795d5354193088573652c9aa6d3a51ff6f695feb92135652744ba161241cf96ef7aa30ac81f01f9c39f14dbfd69211fba4298e5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
